### ISSUE TITLE
 Failed to read file citation.json

### ISSUE THREAD

**Issue by AlexFanC** [linqs/neupsl-ijcai23#1]
Hello, sorry to bother you. When I run run.sh under the cli of the citation task, citation.json is missing. How to solve this problem? I don’t see the relevant generation of citation.json in create-data.py. code

(myenv) fanyongjun@lab4gpu:~/neu/neupsl-ijcai23-main/citation/cli$ ./run.sh
Data experiment::citeseer found cached, skipping download and extract.
Data experiment::cora found cached, skipping download and extract.
Using PSL jar found at /data/fanyongjun/neu/neupsl-ijcai23-main/citation/cli/psl-cli-2.4.0.jar. To fetch a new version, delete this cached jar.
Running PSL Inference.
Unexpected exception!
java.lang.RuntimeException: Failed to read file contents from: '/data/fanyongjun/neu/neupsl-ijcai23-main/citation/cli/citation.json'.
        at org.linqs.psl.util.FileUtils.readFileAsString(FileUtils.java:196)
        at org.linqs.psl.runtime.RuntimeConfig.fromFile(RuntimeConfig.java:417)
        at org.linqs.psl.cli.Launcher.convertRuntimeOptions(Launcher.java:48)
        at org.linqs.psl.cli.Launcher.run(Launcher.java:126)
        at org.linqs.psl.cli.Launcher.main(Launcher.java:142)
        at org.linqs.psl.cli.Launcher.main(Launcher.java:130)
Caused by: java.nio.file.NoSuchFileException: /data/fanyongjun/neu/neupsl-ijcai23-main/citation/cli/citation.json
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3206)
        at org.linqs.psl.util.FileUtils.readFileAsString(FileUtils.java:193)
        ... 5 more
ERROR: Failed to run inference.

**Comment by dickensc** [comment]
It looks like you are directly executing the run script from the `cli` of the experiment directory. This is not the suggested method for reproducing the NeuPSL experiments from the IJCAI 2023 paper. The `citation.json` file the error message is referring to is missing in your `neupsl-ijcai23-main/citation/cli` directory. This file is created by the `neupsl-ijcai23-main/scripts/run.sh` script.

Please see the `NeuPSL Experiments` section of the `README.md` for instructions on reproducing experiments from the IJCAI 2023 paper.
You will first need to generate data, as instructed in the `neupsl-ijcai23-main/citation/README.md` and then run `./scripts/run.sh citation` for the citation network node classification experiments.
